# Generated by Django 2.0.7 on 2018-09-17 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=75, verbose_name='Nome do País')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('imagem_pais', models.ImageField(upload_to='paises/', verbose_name='Imagem do País')),
                ('testemunha_um_nome', models.CharField(max_length=75, verbose_name='Nome da Testemunha Um')),
                ('testemunha_um_fala', models.TextField(verbose_name='Fala da Testemunha Um')),
                ('testemunha_um_imagem', models.ImageField(upload_to='testemunhas/', verbose_name='Imagem da Testemunha Um')),
                ('testemunha_dois_nome', models.CharField(max_length=75, verbose_name='Nome da Testemunha Dois')),
                ('testemunha_dois_fala', models.TextField(verbose_name='Fala da Testemunha Dois')),
                ('testemunha_dois_imagem', models.ImageField(upload_to='testemunhas/', verbose_name='Imagem da Testemunha Dois')),
                ('pais_um_imagem', models.ImageField(upload_to='paises/', verbose_name='Bandeira do País Um')),
                ('pais_dois_imagem', models.ImageField(upload_to='paises/', verbose_name='Bandeira do País Dois')),
                ('pais_dois', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paisdois', to='jogo.Pais', verbose_name='País Dois')),
                ('pais_um', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paisum', to='jogo.Pais', verbose_name='País Um')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pais', to='jogo.Pais', verbose_name='País')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Salvamento',
                'verbose_name_plural': 'Salvamentos',
                'ordering': ['criado_em'],
            },
        ),
    ]
