# Generated by Django 2.0.7 on 2018-09-17 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='pais_dois',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='paisdois', to='jogo.Pais', verbose_name='País Dois'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='pais_dois_imagem',
            field=models.ImageField(blank=True, upload_to='paises/', verbose_name='Bandeira do País Dois'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='pais_um',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='paisum', to='jogo.Pais', verbose_name='País Um'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='pais_um_imagem',
            field=models.ImageField(blank=True, upload_to='paises/', verbose_name='Bandeira do País Um'),
        ),
    ]
